{% set name = "warpfield" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/warpfield-{{ version }}.tar.gz
  sha256: 80a1f57613002f5ff05fcf18b75989fec870373bc73ef7af5f68a09b8fadfd89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - cupy
    - cuda-nvcc
    - tqdm
    - pydantic
    - pyyaml
    - h5py
    - hdf5plugin
    - nibabel
    - tifffile
    - imageio
    - imageio-ffmpeg
    - scikit-image

test:
  requires:
    - pytest
  commands:
    - pytest -q --disable-warnings --maxfail=1 tests/
  pip_check: false


about:
  home: https://github.com/danionella/warpfield
  summary: GPU-accelerated 3D non-rigid registration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bjudkewitz
