{% set name = "warpfield" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/warpfield-{{ version }}.tar.gz
  sha256: 8a3bd67b00fc2f6c8ef30b6eca98ecfdf7ddd05efce7015766da43ee296d446b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - cupy
    - cuda-nvcc
    - tqdm
    - pydantic
    - pyyaml
    - h5py
    - hdf5plugin
    - nibabel
    - tifffile
    - pynrrd
    - zarr
    - imageio
    - imageio-ffmpeg
    - scikit-image

test:
  imports:
    - warpfield
  commands:
    - python -c "import warpfield"
    # - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/danionella/warpfield
  summary: GPU-accelerated 3D non-rigid registration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bjudkewitz
